version: '3'

services:
  rasa-faq:
    container_name: rasa-faq
    image: rasa-faq:latest
    build: ./Dockerfiles/faq
    ports:
      - "5005:5005"
    networks:
      - code-network
    restart: always
networks:
  code-network:
    driver: bridge